table 'Coffee Ranking'
	lineageTag: 94e2fc96-6f6c-4cf4-822e-2c3d5f3bb85d

	column Coffee
		dataType: string
		lineageTag: 5d661ac6-e0c7-475c-99ba-13e2540cb584
		summarizeBy: none
		sourceColumn: Coffee

		annotation SummarizationSetBy = Automatic

	column '# Votes'
		dataType: int64
		formatString: 0
		lineageTag: dff34b4a-6999-4561-baa4-a6974ba829d8
		summarizeBy: sum
		sourceColumn: # Votes

		annotation SummarizationSetBy = Automatic

	column Rank
		dataType: int64
		formatString: 0
		lineageTag: b796fdce-9090-44e3-8b61-4c01743c1dce
		summarizeBy: sum
		sourceColumn: Rank

		annotation SummarizationSetBy = Automatic

	partition 'Coffee Ranking' = m
		mode: import
		source =
				let
				    Source = coffee_dataset_cleaned,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Submission ID", "Favourite Coffee"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Grouped Rows" = Table.Group(#"Removed Duplicates", {"Favourite Coffee"}, {{"# Votes", each Table.RowCount(_), Int64.Type}}),
				    #"Sorted Rows" = Table.Sort(#"Grouped Rows",{{"# Votes", Order.Descending}}),
				    #"Added Index" = Table.AddIndexColumn(#"Sorted Rows", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "Rank"}, {"Favourite Coffee", "Coffee"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

